apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: realestate-service
spec:
  selector:
    app: realestate-app
  ports:
    - protocol: "TCP"
      port: 8063 # The port that the service is running on in the cluster
      targetPort: 8072 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 25
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: realestate-app
spec:
  selector:
    matchLabels:
      app: realestate-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: realestate-app
    spec:
      containers:
        - name: realestate-app
          image: realestate:1.0.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8072 # The port that the container is running on in the cluster
      nodeSelector:
        "kubernetes.io/os": linux